Updates to the README file.
IBM/watson-document-classifier pull request #12
Opened 2017-08-09 22:18 UTC by scottdangelo

Some changes to the README for grammar and style.

2017-08-09 23:21 UTC, markstur requested changes
see comments

2017-08-09 23:21 UTC, markstur commented on README.md
> +The intended audience for this journey is developers who want to learn a method for augumenting classification metadata obtained from Watson Natural Language Understanding API, in situations when the
s/scarcity/a scarcity/ (I think)
extra space after last comma
s/english/English/

2017-08-09 23:21 UTC, markstur commented on README.md
> +* Click `browse` and navigate to this repo `watson-document-classifier/data/sample_text.txt
Looks like this line and next line are missing the ending back-tick around the file names

2017-08-09 23:21 UTC, markstur commented on README.md
> +The configuration json controls the way the text is classfied. The classification process is divided into stages - Base Tagging and Domain Tagging. The Base Tagging stage can be used to specify keywo
s/classfied/classified/

2017-08-09 23:21 UTC, markstur commented on README.md
> +#### Fix-up variable names for your own data and configuration files
"Fix-up variable names" makes more sense with inserted code like credentials_2 --> credentials_1.  I think this notebook isn't using inserted code here so probably s/Fix-up variable names/Fix-up file names/ or something like that.

2017-08-10 15:00 UTC, scottdangelo commented on README.md
> +The intended audience for this journey is developers who want to learn a method for augumenting classification metadata obtained from Watson Natural Language Understanding API, in situations when the
Done

2017-08-10 15:02 UTC, scottdangelo commented on README.md
> +* Click `browse` and navigate to this repo `watson-document-classifier/data/sample_text.txt
Done.

2017-08-10 15:02 UTC, scottdangelo commented on README.md
> +#### Fix-up variable names for your own data and configuration files
Done.

2017-08-10 15:02 UTC, scottdangelo commented on README.md
> +The configuration json controls the way the text is classfied. The classification process is divided into stages - Base Tagging and Domain Tagging. The Base Tagging stage can be used to specify keywo
Done

2017-08-10 16:55 UTC, stevemar approved these changes
LGTM

2017-08-10 16:55 UTC, stevemart commented on README.md
> +Create the following Bluemix service and name it wdc-NLU-service:
could use backticks here: ``wdc-NLU-service``

2017-08-10 16:56 UTC, stevemart commented
latest revision looks fine to me, thanks for the clean up @scottdangelo

2017-08-10 16:56 UTC, merged